#+TITLE: Counsel Configuration
#+AUTHOR: Luis Victoria
#+PROPERTY: header-args :tangle yes
Counsel is an extension of ~ivy~ and enhances features such as looking for commands, and makes use of Ivy's completion framework capabilities.

* Installation
#+begin_src emacs-lisp
    (use-package counsel
      :after ivy)
#+end_src

* Ignoring Files in search
When searching for files using =M-x counsel-find-file=, you will get results for all existing files. Some files are incredibly annoying and I never have a need to find them. These are (listed with respect to the order on the regex expression):
- =.~undo-tree~=
  - Store file's undo-tree onto disk, used to load tree and undo across sessions
- =#foo#=
  - Emacs backup files
- =.DS_Store=
  - Used in MacOS to store custom attributes of the existing folder

Note that the syntax for regexes in Emacs is different than what you might be used to seeing in Perl.
- ~\\~ is used to begin a regex
- ~\\|~ is used to append regexes

[[https://regex101.com/][regex101]] is an excellent resource to build and test your regex strings.

#+begin_src emacs-lisp
  (setq counsel-find-file-ignore-regexp
        (concat "\\"
                ".~undo-tree~$\\|" ; .~undo-tree~
                ".*#.*#$"))        ; #foo#
#+end_src
