#+TITLE: Emacs Behavior Configuration
#+AUTHOR: Luis Victoria
#+PROPERTY: header-args :tangle yes

* File Handling
** Remove Backup Files
Stop Emacs from creating =foo.bar~= and =#foo.bar#= files while open in a buffer.

#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src

** Require Final Newline
Force every file to terminate with a ~\n~.

#+begin_src emacs-lisp
  (setq mode-require-final-newline t)
#+end_src

* Prompts and Feedback
** Use ~y~ and ~n~ for Prompts
Single press ~y~ and ~n~ instead of typing ~yes~ and ~no~ on prompts.

#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Alert for Invalid Action
When performing an invalid action (e.g. backspacing on first character of document, down arrow on last line, etc.):
- If ~t~, visual cue will show
- If ~nil~, bell will sound
- Default behavior is ~nil~

/NOTE/: On MacOS, this makes a large caution triangle which can be very annoying, so it is disabled.

#+begin_src emacs-lisp
  (cond
   ((eq system-type 'gnu/linux)
    (setq visible-bell t))
   ((eq system-type 'darwin) ; MacOS
    (setq visible-bell nil)))
#+end_src

** Better Help Messages
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/core/helpful.org")
#+end_src

* Completion Frameworks
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/core/ivy.org")
#+end_src

* ~ESC~ Behaviors
** Make ~ESC~ Instantly Responsive
On terminal emacs there is about a 700ms delay switching from insert to normal mode.
- Could also attributed to terminal emulator performance (Alacritty had less delay than WezTerm and Kitty).
*** Evil
#+begin_src emacs-lisp
  (setq evil-esc-delay 0)
#+end_src

*** Emacs 27 and Before
#+begin_src emacs-lisp :tangle no
  (setq escape-delay 0)
#+end_src

*** Emacs 28 and Later
#+begin_src emacs-lisp
  (setq key-escape-delay 0)
#+end_src

*** Terminal Emacs
#+begin_src emacs-lisp
  (setq tty-escape-code-delay 0)
#+end_src

** Make ~ESC~ Abandon Prompts
#+begin_src emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src
