#+TITLE: Emacs Editor Configuration
#+AUTHOR: Luis Victoria
#+PROPERTY: header-args :tangle yes

* UI
** Disable Scrollbar
#+begin_src emacs-lisp
  (scroll-bar-mode -1)
#+end_src

** Disable Menu Bar
By default, Emacs shows the /File/, /Edit/, etc. tabs.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
#+end_src

** Disable Tool Bar
By default, displays icons for /New File/, /Open Directory/, /Save/, etc. even if menu bar is disabled.

#+begin_src emacs-lisp
  (tool-bar-mode -1)
#+end_src

** Disable Tooltips
Tooltips pop up when hovering over an element and display additional help information.

~helpful~ replaces this functionality.

#+begin_src emacs-lisp
  (tooltip-mode -1)
#+end_src

* Visual Enhancements
** Theme
#+begin_src emacs-lisp
  (use-package doom-themes
    :init (load-theme 'doom-bluloco-dark t))

  ; TODO: Make the color for the background of text selection more clear
  ; Currently very difficult to see which selection you're on
#+end_src

** Font
/NOTE/: Not applicable to terminal Emacs.

*** Font Face
#+begin_src emacs-lisp
  (defun lv/set-font (font-list height)
    "Set the first available font from FONT-LIST with HEIGHT"
    (when (display-graphic-p)
      (catch 'font-found
        (dolist (font font-list)
          (when (find-font (font-spec :name font))
            (set-face-attribute 'default nil :font font :height height)
            (throw 'font-found font)))
        (message "No font from the list is available!"))))
#+end_src

*** Font Size
#+begin_src emacs-lisp
  (cond
   ((eq system-type 'gnu/linux)
    (lv/set-font '("PragmataPro Mono Liga" "Hack" "DejaVu Sans Mono") 120))
   ((eq system-type 'darwin) ; MacOS
    (lv/set-font '("PragmataPro Mono Liga" "Hack" "DejaVu Sans Mono") 200)))
#+end_src

** Icons
Enable icons via specialized fonts

#+begin_src emacs-lisp
  (use-package all-the-icons)
#+end_src

/NOTE/: When running this configuration for the first time, you will need to run the following:

#+begin_src emacs-lisp :tangle no
  M-x all-the-icons-install-fonts
  M-x nerd-icons-install-fonts
#+end_src

** Modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :custom (doom-modeline-height 15))
#+end_src

** Rainbow Delimiters
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src


* Layout and Margins
** Line Spacing
Per buffer line spacing.

#+begin_src emacs-lisp
  (setq-default line-spacing 0.1)
#+end_src

** Top Padding
Setting format to empty string ~" "~ gives you top padding. Changing the header line face height will change the spacing.

#+begin_src emacs-lisp
  (setq header-line-format " ")
#+end_src

** Side Padding
#+begin_src emacs-lisp
  (lambda ()
    (progn
      (setq left-margin-width 2)
      (setq right-margin-width 2)
      (set-window-buffer nil (current-buffer))))
#+end_src

** Fringe Space
Add fringe space to the left and right of the buffer.

#+begin_src emacs-lisp
  (set-fringe-mode 10)
#+end_src

* Display Settings
** Line Numbers
*** Enable Line Numbers
#+begin_src emacs-lisp
  (global-display-line-numbers-mode t)
#+end_src

**** Exceptions
Otherwise, you get line numbers on things that don't make sense like ~eshell~.

#+begin_src emacs-lisp
  (dolist (mode '(treemacs-mode-hook))
    (add-hook mode (lambda ()
                     (display-line-numbers-mode 0))))
#+end_src

*** Use Relative Line Numbers
#+begin_src emacs-lisp
  (setq display-line-numbers-type 'relative)
#+end_src

*** Display Horizontal Character Position
#+begin_src emacs-lisp
  (setq column-number-mode t)
#+end_src

*** Set Line Number Width
There is some annoying behavior where once you scroll to a line number with an extra digit, the entire code buffer will shift one character to the right to accomodate for this new line number digit.

Instead, we will set the size of this to be the maximum amount of digits necessary for our document, and then fix this in size.

#+begin_src emacs-lisp
  (setq display-line-numbers-width-start t)

  ;; FIXME: This is not working; saw a bug when editing a =.org= file
  ;;          weirdly, this doesn't happen to this config
  
  ;; TODO: Document this bug on GitHub issues
#+end_src

** Enable Text Wrapping
#+begin_src emacs-lisp
  (add-hook 'text-mode-hook 'visual-line-mode)
#+end_src

* ~undo-tree~
#+begin_src emacs-lisp
  (use-package undo-tree
    :ensure t
    :init
    ; (setq undo-tree-auto-save-history nil) ; Disable persistent history
    (global-undo-tree-mode 1))

  ; TODO: Make buffer width for calling undo-tree significantly thinner
#+end_src

#+begin_src emacs-lisp
  (lv/leader-keys
    "u" '(undo-tree-visualize :which-key "undo tree"))

  ; TODO: Make buffer less wide. Doesn't need to take half of the screen
#+end_src
