#+TITLE: LV's Emacs Configuration
#+AUTHOR: Luis Victoria
#+PROPERTY: header-args :tangle yes

/Literate Emacs Config Entrypoint/

** Load External Config Files
This configuration is modularized for maintainability.

#+begin_src emacs-lisp
  (defun lv/org-babel-load-file (file-path)
    "Load an org-babel file from the root emacs config directory."
    (org-babel-load-file
     (expand-file-name
      (concat user-emacs-directory file-path))))
#+end_src


** Launch Emacs with ~PATH~ Environment Variables
MacOS requires additional an additional package to launch Emacs with the correct environment variables

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :if (memq window-system '(mac ns x))
    :config
    (exec-path-from-shell-initialize))
#+end_src


** Keybindings
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/keybinding/keybinding.org")
#+end_src


** Org-mode
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/org-mode/org-mode.org")
#+end_src


** Evil-mode
Use Vim keybindings.

#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/evil-mode.org")
#+end_src


** Modify/Enhance Emacs Behaviors and Core Functionality
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/core/core.org")
#+end_src


** Modify/Enhance Editor
Modifies default settings and extends editor functionality.

#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/editor/editor.org")
#+end_src


** Modify/Enhance UI
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/ui/ui.org")
#+end_src


** Git
#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/git/git.org")
#+end_src


** Programming
LSP and language specific settings.

#+begin_src emacs-lisp
  (lv/org-babel-load-file "src/programming/programming.org")
#+end_src


* TODO Future Features to add
- Maybe add workspaces (on top of tabs)
- Replicate /oil.nvim/
- Migrate away from /lsp-mode/ to something like /lsp-bridge/

* TODO Non-obvious things to fix
- Pressing the tab character in terminal emacs does not result in an indent behavior
  - This should happen if there's no autocomplete box to fill
  - This behavior does not happen in Makefile
  - This happens in Python, Org-mode
